apiVersion: v1
kind: Secret
metadata:
    creationtimestamp: null
    name: kbot
    namespace: kbot_demo
data:
    token: ENC[AES256_GCM,data:klZEySsbEjXab5EnMu+8rl9VB0QiNUWhRp9Vrx36ySAYmsmN1uArE+jO99Te0JhmeAGchQsEV0AiJaq6i6qe7A==,iv:kuQFjMXZ29BRAn89pa4EAuxRTNc/nWDHgsNlFrApH3Y=,tag:bD1PuSHVO5Be4JLeUDg0dw==,type:str]
sops:
    kms: []
    gcp_kms:
        - resource_id: projects/learning-405310/locations/global/keyRings/sops-flux/cryptoKeys/sops-key-flux
          created_at: "2024-01-12T08:50:08Z"
          enc: CiQA1CTqYSZTB/IRWK22vyVtfQf9vJy8NtRYFN+SxGGWj7JKbycSSQBfFVuoHFDatgoiXrfzFkHrQ6GkXSTWXF/CBK5jLaRblZ1UyhAhKZEV8b6ddNdJNfkI56yLeouw9/tknzKWIo+Rx4ym214n9ZA=
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-01-12T08:50:09Z"
    mac: ENC[AES256_GCM,data:+/6lcKRnQI8CmuVbb4ZPFEibeee1dT5VvgzqSp4W5C20Z/T+CJn0Akfgi2BmLxbX6V0lcx7zpKBc3uo+/Gn5IrkTDtHOGAwYwkndyxMi59HAsZcz4bAbk2FcIgDBX5q0YKIfgJ51Oh9amch+FeC1ECUabzbheWAGIlNBTp+R+9c=,iv:vVUawnKty+w1XqezPO74f9qBhnrnExZ+ZlqjvnpBLTs=,tag:T6Qv+wJL3VpIyviMemk77g==,type:str]
    pgp: []
    encrypted_regex: ^(token)$
    version: 3.7.3
