name: Encrypt Secret Manifest and Save in Repository

on:
  push:
    branches:
      - main

jobs:
  encrypt_and_save:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
      id-token: 'write'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: 'Authenticate to Google Cloud'
        uses: 'google-github-actions/auth@v2'
        with:
          project_id: 'learning-405310'
          workload_identity_provider: 'projects/307830987280/locations/global/workloadIdentityPools/github/providers/actions'
          service_account: 'actions@learning-405310.iam.gserviceaccount.com'

      - name: 'secrets'
        uses: 'google-github-actions/get-secretmanager-secrets@v2'
        with:
            secrets: |-
              token:learning-405310/TELE_TOKEN

      # Example of using the output
      #- name: 'publish'
      #  uses: 'foo/bar@v1'
      #  env:
      #    TOKEN: '${{ steps.secrets.outputs.token }}'

      - name: Install SOPS
        run: |
          curl -LO https://github.com/getsops/sops/releases/download/v3.7.3/sops-v3.7.3.linux.amd64
          chmod +x ./sops-v3.7.3.linux.amd64
          sudo mv ./sops-v3.7.3.linux.amd64 /usr/local/bin/sops

      - name: Create Kubernetes Secret Manifest
        run: |
          echo -e "apiVersion: v1 \nkind: Secret \nmetadata: \n  creationtimestamp: null \n  name: kbot \n  namespace: kbot_demo \ndata: \n  token: ${{ steps.secrets.outputs.token }}" > secret.yaml

      - name: Encrypt Secret Manifest
        run: |
          sops -e -gcp-kms projects/learning-405310/locations/global/keyRings/sops-flux/cryptoKeys/sops-key-flux --encrypted-regex '^(token)$' secret.yaml > secret-enc.yaml

      - name: Commit encrypted manifest to the repository
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add secret-enc.yaml
          git commit -m "Add encrypted secret manifest"
          git push origin main
