name: Encrypt Secret Manifest and Save in Repository

on:
  push:
    branches:
      - main

jobs:
  encrypt_and_save:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install SOPS
        run: |
          curl -LO https://github.com/getsops/sops/releases/download/v3.8.1/sops-v3.8.1.linux.amd64
          chmod +x ./sops-v3.8.1.linux.amd64
          sudo mv ./sops-v3.8.1.linux.amd64 /usr/local/bin/sops

      - name: Decrypt Kubernetes Secret Manifest
        run: |
          echo "apiVersion: v1
             kind: Secret
             metadata:
              creationtimestamp: null
              name: kbot
              namespace: kbot_demo
             data:
               token: ${{ secrets.TELE_TOKEN }}" > secret.yaml

      - name: Download SOPS Configuration
        run: |
          curl -o sops_config.yaml https://raw.githubusercontent.com/dm-ol/flux-sops/main/sops_config.yaml

      - name: Encrypt Secret Manifest
        run: |
          sops --config sops_config.yaml -e --in-place --encrypted-regex '^(token)$' secret.yaml > secret-enc.yaml

      - name: Commit encrypted manifest to the repository
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git add secret-enc.yaml
          git commit -m "Add encrypted secret manifest"
          git push origin main
